theme: jekyll-theme-slate
title: DNS flag day
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
sitemap:
file: "/sitemap.xml"
defaults:
  -
    scope:
      path: ""
      type: "pages"
  -
    scope:
      path: "2019"
      type: "pages"
  -
    scope:
      path: "2020"
      type: "pages"
